---
- name: Copy a file to remote servers
  hosts: all
  become: yes
  tasks:
    - name: Copy file to remote server
      copy:
        src: /path/to/local/file.txt
        dest: /path/to/remote/file.txt
        mode: '0777'     # Set file permissions to be readable, writable, and executable by all users
        owner: root      # Set file owner to root or another specified user name like (raj, jay, etc.)