---
- name: Install nginx on Amazon Linux 2023 and deploy website
  hosts: all
  become: yes

  tasks:
    # task 1: Install nginx using dnf
    - name: Install nginx using dnf
      dnf:
        name: nginx
        state: present
      notify: restart nginx service
# task 2: Enable nginx service
    - name: Enable nginx service
      service:
        name: nginx
        enabled: yes
# task 3: Copy index.html to nginx default path
    - name: Copy index.html to nginx default path
      copy:
        src: index.html
        dest: /usr/share/nginx/html/index.html
      notify: restart nginx service
# task 4: start nginx service 
  handlers:
    - name: restart nginx service
      service:
        name: nginx
        state: restarted
